/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Author: typeof import('./../src/components/author.vue')['default']
    CommonPagination: typeof import('./../src/components/CommonPagination.vue')['default']
    CommonTable: typeof import('./../src/components/CommonTable.vue')['default']
    Empty: typeof import('./../src/components/Empty.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/SvgIcon.vue')['default']
  }
}
