/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CommonDatePicker: typeof import('./../src/components/CommonDatePicker.vue')['default']
    CommonDrawer: typeof import('./../src/components/CommonDrawer.vue')['default']
    CommonPagination: typeof import('./../src/components/CommonPagination.vue')['default']
    CommonTable: typeof import('./../src/components/CommonTable.vue')['default']
    CommonTitle: typeof import('./../src/components/CommonTitle.vue')['default']
    CommonUpload: typeof import('./../src/components/CommonUpload.vue')['default']
    CustomChartBar: typeof import('./../src/components/CustomChartBar/index.vue')['default']
    CustomChartLine: typeof import('./../src/components/CustomChartLine/index.vue')['default']
    CustomChartPie: typeof import('./../src/components/CustomChartPie/index.vue')['default']
    CustomEditDialog: typeof import('./../src/components/CustomEditDialog/index.vue')['default']
    CustomForm: typeof import('./../src/components/CustomForm/index.vue')['default']
    CustomMoveCard: typeof import('./../src/components/CustomMoveCard/index.vue')['default']
    CustomSearch: typeof import('./../src/components/CustomSearch/index.vue')['default']
    CustomTable: typeof import('./../src/components/CustomTable/index.vue')['default']
    Empty: typeof import('./../src/components/Empty.vue')['default']
    IconDate: typeof import('./../src/components/icons/IconDate.vue')['default']
    IconOrganization: typeof import('./../src/components/icons/IconOrganization.vue')['default']
    MyDateTimePicker: typeof import('./../src/components/MyDateTimePicker/index.vue')['default']
    MyInput: typeof import('./../src/components/MyInput/index.vue')['default']
    MySelect: typeof import('./../src/components/MySelect/index.vue')['default']
    MyTree: typeof import('./../src/components/MyTree/index.vue')['default']
    NormalCard: typeof import('./../src/components/CustomCard/NormalCard.vue')['default']
    RichEdit: typeof import('./../src/components/RichEdit/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/SvgIcon.vue')['default']
  }
}
